### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by pixelstrolch** [WPZOO/penguin-gold#27]
# Design
- [ ] Fix empty space if there is only the standard category and no tags

# Accessibility
- [ ] Check out better styling for focus 
- [ ] Make submenu links visible when focused via tab
- [ ] Do tests using tab for reading order and with forms
- [ ] Check machine-readable text for buttons

**Comment by pixelstrolch** [comment]
Close this and create separate issues for better tracking and assigning. #28 #29
